### ISSUE TITLE
SSL Cert issue?

### ISSUE THREAD

**Issue by tshamilton** [CharlesBlonde/libpurecoollink#20]
Hi all,

It might be me, but I hope someone can point me in the right direction. I'm getting an InsecureRequestWarning from the urllib3 package when I attempt to connect to Dyson. See below:

python 3.6.4
```
>>> from libpurecoollink.dyson import DysonAccount
>>> dyson_account = DysonAccount("my_example_email@gmail.com", "yeahnah", "AU")
>>> logged = dyson_account.login()
C:\xampp\python\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
>>>
```

I should point out that the connection works, but every call to Dyson gets this message, and it seems reckless to just ignore it. Any suggestions on how I can get this connection to work properly?

**Comment by exking** [comment]
Problem is mostly on Dyson side, try https://api.cp.dyson.com in your browser - you'll get invalid (self-signed) certificate warning.

**Comment by tshamilton** [comment]
Good call, might be easier to turn off the warning then. Thanks @exking !
