### ISSUE TITLE
unable to login to dyson account

### ISSUE THREAD

**Issue by pritamqu** [CharlesBlonde/libpurecoollink#26]
hi,

I am unable to log in using below command:

from libpurecoollink.dyson import DysonAccount
dyson_account = DysonAccount("<name@email.id>","<password>","<EN>")
logged = dyson_account.login()

any help is appreciated.

**Comment by pritamqu** [comment]
it solved

**Comment by AnastasiiaMishchenko** [comment]
@pritamqu how did you solve the problem? I have the same one
